//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby_history.proto
/// <reference path="common.ts" />

module Cmd {
	/**
	 * 各个玩家战绩数据
	 */
	export class UserGameHistory {
		/**
		 * 玩家昵称
		 */
		nickName: string;
		/**
		 * 积分可能为负 所以为int32
		 */
		integral: number;
		/**
		 * 头像,茶馆用
		 */
		headUrl: string;
		GetType(): string { return 'Cmd.UserGameHistory'; }
	}
	/**
	 * 比赛场战绩数据
	 */
	export class MatchGameHistory {
		/**
		 * 名次
		 */
		rank: number;
		/**
		 * 第几轮
		 */
		round: number;
		/**
		 * 比赛场次id
		 */
		playId: number;
		/**
		 * 奖励
		 */
		award: string;
		GetType(): string { return 'Cmd.MatchGameHistory'; }
	}
	/**
	 * 战绩数据
	 */
	export class GameHistory {
		/**
		 * 全局唯一的房间id 用于索引战绩数据 （不用于显示）
		 */
		globalRoomId: number;
		/**
		 * 该战绩的房间号(组建房间时 随机的房间号)
		 */
		roomId: number;
		/**
		 * 对战时间
		 */
		timeStamp: number;
		/**
		 * 四个玩家的对战积分详情
		 */
		userGameHistorys: UserGameHistory[];
		/**
		 * 比赛场的相关数据
		 */
		matchGameHistory: MatchGameHistory;
		/**
		 * 发送gameId
		 */
		gameId: number;
		GetType(): string { return 'Cmd.GameHistory'; }
	}
	/**
	 * 详细战绩数据
	 */
	export class GameHistoryDetail {
		/**
		 * 具体游戏时间
		 */
		timeStamp: number;
		/**
		 * 四个玩家的对战积分详情
		 */
		userGameHistoryDetails: UserGameHistory[];
		/**
		 * 分享数据
		 */
		shareInfo: Cmd.ShareInfo;
		GetType(): string { return 'Cmd.GameHistoryDetail'; }
	}
	/**
	 * 战绩统计数据获取
	 */
	export class GetGameDataHistoryCmd_C {
		/**
		 * 分页处理 当前请求第几页 默认一页返回10个数据
		 */
		curPage: number;
		/**
		 * 某一个匹配号的战绩
		 */
		matchId: number;
		/**
		 * 某一个房间号的战绩
		 */
		roomId: number;
		GetType(): string { return 'Cmd.GetGameDataHistoryCmd_C'; }
	}
	export class GetGameDataHistoryCmd_S {
		/**
		 * 返回码 默认0为操作成功
		 */
		resultCode: number;
		/**
		 * 当前第几页
		 */
		curPage: number;
		/**
		 * 总共几页
		 */
		maxPage: number;
		/**
		 * 战绩统计数据
		 */
		gameHistroys: GameHistory[];
		/**
		 * 某一个匹配号的战绩
		 */
		matchId: number;
		GetType(): string { return 'Cmd.GetGameDataHistoryCmd_S'; }
	}
	/**
	 * 获取指定 globalRoomId 的 所有具体牌局详细数据
	 */
	export class GetGameDetailHistoryCmd_C {
		/**
		 * 全局唯一的房间id 用于索引战绩数据
		 */
		globalRoomId: number;
		GetType(): string { return 'Cmd.GetGameDetailHistoryCmd_C'; }
	}
	export class GetGameDetailHistoryCmd_S {
		/**
		 * 返回码 默认0为操作成功
		 */
		resultCode: number;
		/**
		 * 全局唯一的房间内的 所有游戏数据
		 */
		gameHistroyDetails: GameHistoryDetail[];
		/**
		 * 房主小费数据
		 */
		gameHostTip: GameHistoryDetail;
		/**
		 * 发送gameId
		 */
		gameId: number;
		GetType(): string { return 'Cmd.GetGameDetailHistoryCmd_S'; }
	}
	/**
	 * 房间日志
	 */
	export class RoomLogHistory {
		/**
		 * 时间
		 */
		sec: number;
		/**
		 * 时间
		 */
		round: number;
		/**
		 * 描述
		 */
		desc: string;
		GetType(): string { return 'Cmd.RoomLogHistory'; }
	}
	/**
	 * 请求房间日志信息
	 */
	export class GetRoomLogHistoryCmd_C {
		/**
		 * 房间id,matchId
		 */
		roomId: number;
		/**
		 * 全局唯一的房间id 用于索引战绩数据
		 */
		globalRoomId: number;
		GetType(): string { return 'Cmd.GetRoomLogHistoryCmd_C'; }
	}
	/**
	 * 返回请求房间日志信息
	 */
	export class GetRoomLogHistoryCmd_S {
		/**
		 * 房间id,matchId
		 */
		roomId: number;
		/**
		 * 全局唯一的房间id 用于索引战绩数据
		 */
		globalRoomId: number;
		/**
		 * 全局唯一的房间id 用于索引战绩数据
		 */
		list: RoomLogHistory[];
		GetType(): string { return 'Cmd.GetRoomLogHistoryCmd_S'; }
	}
}
